Desc = output.spg
Start = #8000		; адрес старта
Stack = #c000		; начальное расположение стека
Resident = #5b00	; расположение резидента для запуска спгешечки
Page3 = 0		; начальная страница 
Clock = 2		; скорость процессора. 0 - 3,5МГц / 1 - 7МГц /2 - 14МГц / 3 - 14МГц оверклокед
INT = 0			; прерывания выключены
Pager = 0		; адрес менеджера страниц, 0 - без менеджера 

; RAM #05
Block = #4000, #05, bin/page5.C

; RAM #02
Block = #8000, #02, bin/page2.C

; RAM #00
Block = #c000, #00, bin/page0.C


